### ISSUE TITLE
Bindings for Material Renderer Color - Renderer does not work

### ISSUE THREAD

**Issue by RubenHooijer** [Juce-Assets/Juce-TweenPlayer#3]
I tried creating a bindable for Material Renderer Color - target, but it just doesn't work, the whole component starts giving errors and I'd have to delete the whole component to fix it.

Steps to reproduce:
1. Create bindable data which has a Renderer variable in it
2. Select bindable data
3. Add Component->Material Renderer->Color
4. Click the checkbox in front of target

**Comment by Guillemsc** [comment]
Hi @RubenHooijer, nice catch! 
I could reproduce it and got fixed on new version [1.37](https://github.com/Juce-Assets/Juce-TweenPlayer/releases/tag/1.3.7).
Thanks :)
